### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by kodisj** [barnjamin/arc3.xyz#4]
When i do yarn install and yarn start, i am seeing this error.

Starting the development server...

<--- Last few GCs --->

[18707:0x64ec730]   403577 ms: Mark-sweep (reduce) 2045.5 (2082.7) -> 2044.2 (2083.0) MB, 7940.2 / 0.1 ms  (average mu = 0.081, current mu = 0.006) allocation failure scavenge might not succeed
[18707:0x64ec730]   411062 ms: Mark-sweep (reduce) 2045.7 (2083.2) -> 2044.4 (2083.2) MB, 7470.7 / 0.1 ms  (average mu = 0.043, current mu = 0.002) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xafcff0 node::Abort() [/usr/local/lib/node_modules/node/bin/node]
 2: 0xa14113 node::FatalError(char const*, char const*) [/usr/local/lib/node_modules/node/bin/node]
 3: 0xce5c7e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/lib/node_modules/node/bin/node]
 4: 0xce5ff7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/lib/node_modules/node/bin/node]
 5: 0xeb4495  [/usr/local/lib/node_modules/node/bin/node]
 6: 0xeb4f76  [/usr/local/lib/node_modules/node/bin/node]
 7: 0xec2f2e  [/usr/local/lib/node_modules/node/bin/node]
 8: 0xec3950 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/lib/node_modules/node/bin/node]
 9: 0xec67be v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/lib/node_modules/node/bin/node]
10: 0xe881ea v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/lib/node_modules/node/bin/node]
11: 0x11fd286 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/lib/node_modules/node/bin/node]
12: 0x15e67d9  [/usr/local/lib/node_modules/node/bin/node]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by barnjamin** [comment]
Are you running it on a resource constrained machine? VM with v low ram or raspi or something?

**Comment by barnjamin** [comment]
https://github.com/web3-storage/web3.storage/issues/549 might be this

**Comment by barnjamin** [comment]
closing as stale
